"""empty message

Revision ID: 905f5fa6cd06
Revises: bbd465382c7e
Create Date: 2022-05-11 08:42:40.420515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905f5fa6cd06'
down_revision = 'bbd465382c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', 'passwork')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passwork', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
